server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
    fetch-registry: true
  instance:
    hostname: localhost
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lwb_data?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  #如果没有表，就创建；若存在，则更新
    properties:
      hibernate.format_sql: true  #格式化sql
  resources:
    static-locations: file:${file.upload.dir}
file:
  upload:
    dir: E:/pic/